export default {
	dropFileHereOrSelectFile: 'Drop file here, or <link>Select File</link>',
	supportedFileTypes: 'Only <typeList>and</typeList> file types are supported',
	upload: 'Upload',
	confirm: 'Confirm',
	cancel: 'Cancel',
	continue: 'Continue',
	validate: 'Validate',
	select: 'Select',
	selected: 'Selected',
	submit: 'Submit',
	update: 'Update',
	change: 'Change',
	tryAgain: 'Try Again',
	approve: 'Approve',
	search: 'Search',
	all: 'All',
	typeHere: 'Type Here',
	showAll: 'Show All',
	showMore: 'Show more',
	showLess: 'Show less',
	selectReason: 'Select Reason',
	selectAll: 'Select All',
	apply: 'Apply',
	noOptions: 'No "{counterLabel}" Found',
	goToHome: 'Go to Homepage',
	perMonth: 'PM',
	currencyZar: 'R',
	filters: 'Filters',
	filtersAndSort: 'Filter & sort',
	sortByDesktop: 'Sort by:',
	sortBy: 'Sort by',
	openFilterDrawer: 'Open filter drawer',
	closeFilterDrawer: 'Close filter drawer',
	stillHaveQuestions: 'Still have questions?',
	orCallUsAt: 'or call us at',
	tsaPhoneNumber: '10213',
	noMatchingProducts: 'No matching {productType} under category: {category}',
	noProducts: 'No {productType} under category: {category}',
	tryClearingFilters: 'Try clearing your filters or selecting another category',
	noDevicesMatchFilters: 'No {productType} match your current filters',
	tryAdjustingFilters: 'Try adjusting your selections or clearing some filters',
	close: 'Close',
	deviceDetailsPage: 'device_details_page',
	cartPage: 'cart_page',
	cartBlockedTitle: 'Your cart is already full',
	cartBlockedMessage: 'You can only have one service in your cart at a time.',
	cartBlockedMessage2: 'View your cart and clear it to add this new service.',
	viewCart: 'View cart',
	addToCart: 'Add to cart',
	shopHome: 'Shop home',
	sms: 'SMS',
	yourID:'Your ID',
	yourPassport:'Your passport number',
	verificationFailed: 'That didn\'t work this time',
	letsConfirmItsReallyYou: 'Let\'s confirm it\'s really you',
	continueHere: 'Continue here',
	facialScanSecurityMessage: 'For security reasons, we\'ll do a quick facial scan to match your photo with your ID.',
	yourPhoneNumber: 'Phone number',
	verifyYourIdentity: 'Verify your identity',
	ifItStillDoesntWork: 'If it still doesn\'t work, we can have one of our agents call you to complete the order',
	verificationFailedMessage: 'We couldn\'t verify your face just now - it happens!',
	blockMessageText: 'Try again in better lighting, or remove anything that might block your face.',
	iveCompletedTheFacialScan: 'I\'ve completed the facial scan',
	requestACallBack: 'Request a call back',
	letsFinishThisTogether: 'Let\'s finish this together',
	facialScanDidntGoThrough: 'Looks like the facial scan didn\'t go through - and that\'s okay.',
	wellHaveOneOfOurAgentsReachOut: 'We\'ll have one of our agents reach out to verify your details and help you complete the order',
	linkResent: 'Link resent!',
	resendLink: 'Resend link',
	youreAllSet: 'You\'re all set!',
	faceVerificationSuccessful: 'Face verification was successful.',
	thanksForYourPatience: 'Thanks for your patience! You can now continue to finish your order',
	checkYourEmailForTheSecureVerificationLink: 'Check your email for the secure verification link',
	weHaventReceivedConfirmationYet: 'We haven\'t received confirmation yet. Please make sure you\'ve completed the scan on your other device.',
	weCouldntVerifyYourIdentity: 'We couldn\'t verify your identity. Please try again or resend the link.',
	completeTheFacialScan: 'We\'ve sent a link to your other device so you can complete the facial scan.',
	onceFinishedConfirmToContinue: 'Once you\'ve finished, come back here and confirm to continue your order',
	didntReceiveTheLink: 'Didn\'t receive the link? It may take a few moments to arrive. Check your spam folder, or resend the link.',
	waitingForVerificationTitle: 'Waiting for verification...',
	weNeedToVerifyYourIdentity: 'We need to verify your identity before you can proceed.',
	chooseVerificationMethod: 'Choose a verification method:',
	facialVerification: 'Facial Verification',
	sendLinkToEmailOrSms: 'Send link to Email or SMS',
	waitingForVerification: 'Waiting for Verification',
	verifyingYourIdentity: 'Verifying your identity...',
	almostThere: 'Almost there, just a moment...',
	stillChecking: 'Still checking, thanks for your patience...',
	pleaseWaitWhileWeVerify: 'Please wait while we verify your facial scan',
	passport: 'Passport',
	pleaseEnterValidPassport:'Please enter a valid passport number',
	passportRequired: 'Passport number is required',
	id: 'ID',
	email: 'E-Mail',
	preferredMethod: 'Preferred Contact Method',
	existingCustomerForm: 'Please fill in a short form and one of our agents will contact you to finalize your order.',
	existingCustomerMessage: 'Please fill in a short form and one of our agents will contact you to finalize your order.',
	ageRequirement: 'You must be 18+',
	existingCustomerHelp: 'You are already a customer with us. Orders for existing customers are completed with the help of an agent.',
	passportsNotSupported: 'Passports not supported',
	existingCustomer: 'You are already a customer',
	startOverWithAnotherID: 'Start over with another ID',
	underageMessage: 'It looks like you are under 18',
	underageRestrictionMessage: 'Only individuals over the age of 18 are allowed to complete the order',
	onlineCheckoutRestriction: 'At the moment, online checkout is only available with a South African national ID.',
	requiredField: 'This field is required',
	sendLinkToAnotherDevice: 'Send link to another device',
	spot: 'Find a well-lit spot',
	removeFromFace: 'Remove anything covering your face',
	cameraWorks: 'Make sure your camera works',
	completeFacialScanOnDevice: 'You can complete the facial scan on this device, or we can send you a link to continue on another device (like your phone).',
	beforeYouStart: 'Before you start',
	sendLink: 'Send link',
	weCanSendYouASecureLink: 'We can send you a secure link so you can complete the face verification on another device (like your smartphone).',
	cameraWarning: 'It looks like this device doesn&apos;t have a camera.',
	pleaseEnterValidID: 'Please enter a valid ID number',
	idRequired: 'ID number is required',
	pleaseEnterValidMobileNumber: 'Please enter a valid mobile number',
	pleaseEnterValidEmailAddress: 'Please enter a valid e-mail address',
	firstName: 'First name',
	newOrExisting: 'New here or already with us -',
	lastName: 'Last name',
	title: 'Title',
	emailAddress: 'E-mail address',
	enterIdAndPassport: 'Enter user ID or passport number so we can guide you through the right setup',
	mobileNumber: 'Mobile number',
	personalInformation: 'Personal information',
	personalInformationHelp: 'This information will help us contact you',
	yourAddress: 'Your address',
	addressHelpText: 'This information will help us contact you',
	residentialAddress: 'Residential address',
	sameAsShippingAddress: 'Use also as shipping address',
	shippingAddress: 'Shipping address',
	searchResidentialAddress: 'Search your residential address',
	cantFindItSearchOnMap: 'Can\'t find it? Search on a map',
	checkingCoverage: 'Checking coverage...',
	failedToLoadScripts: 'Failed to load scripts. Please refresh the page.',
	loading: 'Loading...',
	noResults: 'No Results',
	noResultsFor: 'There were no results found for',
	findNearestAddress: 'Find nearest address',
	noMatchingAddresses: 'No matching addresses',
	pleaseSelectClosestAddress: 'Please select your closest address',
	selectYourAddress: 'Select your address',
	selectShippingAddress: 'Select shipping address',
	selectAddress: 'Select address',
	addressesNear: 'Addresses near:',
	buildingName: 'Building name',
	floor: 'Floor',
	unitNumber: 'Unit / number',
	pleaseSelectAddressFromList: 'Please select an address from the list to continue',
	pleaseSelectYourResidentialAddress: 'Please select your residential address',
	pleaseSelectShippingAddress: 'Please select a shipping address before continuing. You can also use your residential address as the shipping address.',
	addressReadOnlyNote: 'Changes to your address not allowed anymore',
	addressReadOnlyInfoTitle: 'Why can\'t I change my address?',
	addressReadOnlyInfoDescription: 'Your customer account has already been created with this address. If you need to update your address, please contact our support team.',
	building: 'Building',
	note: 'Note',
	personalInfo: 'Personal info',
	address: 'Address',
	bankPayment: 'Bank & payment',
	employment: 'Employment',
	freeIncome: 'Free income',
	orderSummary: 'Order summary',
};
